baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Sarvjot Singh | My Hobbies'
theme = 'ananke'

[params]
  author = "Sarvjot Singh"
  description = "Welcome to my world of hobbies and passions!"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "photography"
    name = "Photography"
    url = "/photography/"
    weight = 2

  [[menu.main]]
    identifier = "reading"
    name = "Reading"
    url = "/reading/"
    weight = 3

  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 4

  [[menu.main]]
    identifier = "coding"
    name = "Coding"
    url = "/coding/"
    weight = 5
